davinstore/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
]

main/urls.py
from django.urls import path
from main.views import show_main
from main.views import show_main, create_product, show_xml, show_json, show_xml_by_id, show_json_by_id, register, login_user, logout_user, hapus, tambah, kurang
app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('create-product', create_product, name='create_product'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'), 
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'), 
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('tambah/<int:item_id>', tambah, name='tambah'),
    path('kurang/<int:item_id>', kurang, name='kurang'),
    path('hapus/<int:item_id>', hapus, name='hapus'),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class Item(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    amount = models.IntegerField()
    description = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

main/forms.py
from django.forms import ModelForm
from main.models import Item

class ProductForm(ModelForm):
    class Meta:
        model = Item
        fields = ["name", "amount", "description"]

main/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from main.forms import ProductForm
from django.urls import reverse
from main.models import Item
from django.http import HttpResponse
from django.core import serializers
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages  
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse 

# Create your views here.
@login_required(login_url='/login')
def show_main(request):
    products = Item.objects.filter(user=request.user)

    context = {
        'name': request.user.username,
        'class': 'PBP B', 
        'products': products,
        'last_login': request.COOKIES['last_login'],
    }

    return render(request, "main.html", context)

def create_product(request):
    form = ProductForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        product = form.save(commit=False)
        product.user = request.user
        product.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "create_product.html", context)

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login')
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("main:show_main")) 
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Sorry, incorrect username or password. Please try again.')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

def show_xml(request):
    data = Item.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = Item.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = Item.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = Item.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def hapus(request, item_id):
    item = Item.objects.filter(id=item_id)
    item.delete()

    return redirect('main:show_main')

def tambah(request, item_id):
    item = Item.objects.filter(id=item_id) 
    for i in item:
        i.amount+=1

    for i in item:
        i.save()

    return redirect('main:show_main')


def kurang(request, item_id):
    item = Item.objects.filter(id=item_id) 
    for i in item:
        i.amount-=1

    for i in item:
        i.save()

    return redirect('main:show_main')

main/templates/create_product.html
{% extends 'base.html' %}

{% block content %}
<style>
    body {
        background-color: brown;
    }
</style>

<body>
    <section class="Add add-custom" >
        <div class="container py-5 h-100">
          <div class="row justify-content-center align-items-center h-100">
            <div class="col-12 col-lg-9 col-xl-7">
              <div class="card shadow-2-strong card-registration" style="border-radius: 15px;">
                <div class="card-body p-4 p-md-5">
                  <h3 class="mb-4 pb-2 pb-md-0 mb-md-5">Add New Product</h3>
                    <form method="POST">
                        {% csrf_token %}
                        <table>
                            {{ form.as_table }}
                            <tr>
                                <td></td>
                                <td>
                                    <input type="submit" value="Add Product"/>
                                </td>
                            </tr>
                        </table>
                    </form>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
</body>
{% endblock %}

main/templates/login.html
{% extends 'base.html' %}

{% block meta %}
    <title>Login</title>
{% endblock meta %}

{% block content %}
    <section class="login" style="background-color: brown;">
        <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col col-xl-10">
            <div class="card" style="border-radius: 1rem;">
                <div class="row g-0">
                <div class="col-md-6 col-lg-5 d-none d-md-block">
                    <img src="https://images.unsplash.com/photo-1511317559916-56d5ddb62563?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8c3RvcmV8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=900&q=60"
                    alt="login form" class="img-fluid" style="border-radius: 1rem 0 0 1rem;" />
                </div>
                <div class="col-md-6 col-lg-7 d-flex align-items-center">
                    <div class="card-body p-4 p-lg-5 text-black">
    
                    <form method="POST" action="">
                        {% csrf_token %}
                        <div class="logo">
                        <span class="h1 fw-bold mb-0">Davin Store</span>
                        </div>
    
                        <h5 class="fw-normal mb-3 pb-3" style="letter-spacing: 1px;">Sign In</h5>
    
                        <div class="form-outline mb-4">
                        <label class="form-label">Username</label>
                        <input type="text" name="username" class="form-control"/> 
                        </div>
    
                        <div class="form-outline mb-4">
                        <label class="form-label">Password</label>
                        <input type="password" name="password" id="form2Example27" class="form-control" />
                        </div>
    
                        <div class="pt-1 mb-4">
                        <button class="btn btn-dark btn-lg btn-block" type="Submit" value="login">Login</button>
                        </div>

                        <p class="mb-5 pb-lg-2" style="color: #393f81;"></p>
                            Don't have an account yet? <a href="{% url 'main:register' %}">Register Here</a>
                    </form>
    
                    </div>
                </div>
                </div>
            </div>
            </div>
        </div>
        </div>
    </section>

{% endblock content %}

main/templates/main.html
{% extends 'base.html' %}

{% block content %}
    <style>
        body {
            background-color: brown;
        }

        .card-body {
            display: flex;
            flex-direction: row;
        }


        .last-card {
            background-color: darkblue; /* Ganti warna sesuai preferensi Anda */
        }
    </style>
    <body>

        <h1>Davin Store</h1>
    
        <h5>Name:</h5>
        <p>{{name}}</p>
    
        <h5>Class:</h5>
        <p>{{class}}</p>
        <h5>Sesi terakhir login: {{ last_login }}</h5>
    
        <a href="{% url 'main:logout' %}">
            <button>
                Logout
            </button>
        </a>
    
        <div>Barang yang kamu tambahkan: {{products|length}}</div>
            
        {% for product in products %}
            <div class="card-product {% if forloop.last %}last-card{% endif %}">
                <div class="col-md-8 col-lg-6 col-xl-4">
                    <div class="card" style="border-radius: 15px;">
                        <div class="card-body pb-0">
                            <div class="d-flex justify-content-between">
                                <div>
                                    <p class="text-dark">{{product.name}}</a></p>
                                    <p class="small text-muted">{{product.description}}</p>
                                </div>
                            </div>
                        </div>
                        <hr class="my-0" />
                        <div class="card-body pb-0">
                            <div class="d-flex justify-content-between">
                                <p class="small text-muted">{{product.amount}}</p>
                            </div>
                            <div style="width: 20px;"></div>
                            <a href="{% url 'main:tambah' product.id %}">
                                <button>
                                    +++
                                </button>
                            </a>

                            <a href="{% url 'main:kurang' product.id %}">
                                <button>
                                    ---
                                </button>
                            </a>
                            <a href="{% url 'main:hapus' product.id %}">
                                <button>
                                    del
                                </button>
                            </a>
                        </div>
                        <hr class="my-0" />
                    </div>
                </div>
            </div>
        {% endfor %}
    
        <a href="{% url 'main:create_product' %}">
            <button>
                Add New Product
            </button>
        </a>
    </body>
{% endblock content %}

main/templates/register.html
{% extends 'base.html' %}

{% block meta %}
    <title>Register</title>
{% endblock meta %}

{% block content %}  

<div class = "login">
    
    <h1>Register</h1>  

        <form method="POST" >  
            {% csrf_token %}  
            <table>  
                {{ form.as_table }}  
                <tr>  
                    <td></td>
                    <td><input type="submit" name="submit" value="Daftar"/></td>  
                </tr>  
            </table>  
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta
            name="viewport"
            content="width=device-width, initial-scale=1.0"
        />
        {% block meta %}
        {% endblock meta %}
    </head>

    <body>
        {% block content %}
        {% endblock content %}
    </body>
</html>